racsonpDemo/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using racsonpDemo.Models;
using System.Reflection;

namespace racsonpDemo.Controllers
{
    public class QueryController : Controller
    {
        public ActionResult Config()
        {

            return View();
        }

        // GET: Query
        public ActionResult Index()
        {

            ViewBag.Active = new List<SelectListItem> {                  
                 new SelectListItem { Text = "EXCEL", Value = "1"},                   
                 new SelectListItem { Text = "CSV", Value = "2"}
             };
            // var model = new ProductModel();
            // return View(model);


            // DataTable dt = new SqlBox().GetData();

            var model = new SqlBox();
            model.Query = "SELECT p.Nombre, p.Precio, p.Tienda, a.FirstName FROM Producto p  JOIN Agent a  on a.Id = p.Id";
            model.Format = 1;
            return View(model);
            // return View();
        }

        public ActionResult Consulta()
        {
            return RedirectToAction("Index");
            //ViewBag.Active = new List<SelectListItem> {                  
            //       new SelectListItem { Text = "EXCEL", Value = "1"},                   
            //       new SelectListItem { Text = "CSV", Value = "2"}
            //   };

            //var sqlBox = new SqlBox { Format = 1 };
            //return View(sqlBox);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Consulta([Bind(Include = "Query, Format")] SqlBox sqlBox, string tipo)
        {

            ViewBag.Active = new List<SelectListItem> {                  
                 new SelectListItem { Text = "EXCEL", Value = "1"},                   
                 new SelectListItem { Text = "CSV", Value = "2"}
             };


            if (String.IsNullOrEmpty(sqlBox.Query))
            {
                return RedirectToAction("Index");
            }


            var result = new SqlBoxExecuter().GetData(sqlBox.Query);
            result.Format = sqlBox.Format;



            if (tipo == "Export")
            {

                Export(result);
                return RedirectToAction("Index");

            }
            else
            {
                return View(result);
            }



        }



        public ActionResult Export(SqlBox sqlBox)
        {

            DataTable dt = sqlBox.DataTable;
            if (sqlBox.Format == 2)
            {
                //http://techbrij.com/export-excel-xls-xlsx-asp-net-npoi-epplus
                Response.Clear();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment;filename=DataTable.csv");
                Response.Charset = "";
                Response.ContentType = "application/text";

                StringBuilder sb = new StringBuilder();

                for (int k = 0; k < dt.Columns.Count; k++)
                {
                    //add separator
                    sb.Append(dt.Columns[k].ColumnName + ',');
                }
                //append new line

                sb.Append("\r\n");

                for (int i = 0; i < dt.Rows.Count; i++)
                {

                    for (int k = 0; k < dt.Columns.Count; k++)
                    {
                        //add separator
                        sb.Append(dt.Rows[i][k].ToString().Replace(",", ";") + ',');
                    }
                    //append new line
                    sb.Append("\r\n");
                }
                Response.Output.Write(sb.ToString());
                Response.Flush();
                Response.End();


            }
            else
            {
                //Create a dummy GridView

                var gridView1 = new GridView
                {
                    AllowPaging = false,
                    DataSource = dt
                };

                gridView1.DataBind();



                Response.Clear();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment;filename=DataTable.xls");
                Response.Charset = "";
                Response.ContentType = "application/vnd.ms-excel";

                StringWriter sw = new StringWriter();
                HtmlTextWriter hw = new HtmlTextWriter(sw);

                for (int i = 0; i < gridView1.Rows.Count; i++)
                {
                    //Apply text style to each Row
                    gridView1.Rows[i].Attributes.Add("class", "textmode");
                }

                gridView1.RenderControl(hw);

                //style to format numbers to string

                string style = @"<style> .textmode { mso-number-format:\@; } </style>";

                Response.Write(style);
                Response.Output.Write(sw.ToString());
                Response.Flush();
                Response.End();

            }
            return RedirectToAction("Index");
        }



        // [HttpPost]
        //  [HttpParamAction]

        //public ActionResult Export([Bind(Include = "Query, Format")] SqlBox sqlBox)
        //{
        //     // var sqlBox =new SqlBox{ Format= format, Query = querry};
        //    ViewBag.Active = new List<SelectListItem> {                  
        //          new SelectListItem { Text = "EXCEL", Value = "1"},                   
        //          new SelectListItem { Text = "CSV", Value = "2"}
        //      };


        //    if (String.IsNullOrEmpty(sqlBox.Query))
        //      // if (String.IsNullOrEmpty(sqlBox.Query))
        //    {
        //        return RedirectToAction("Index");
        //    }

        //    DataTable dt = new SqlBoxExecuter().GetData(sqlBox.Query).DataTable;

        //      if (sqlBox.Format == 2)
        //      {

        //          //http://techbrij.com/export-excel-xls-xlsx-asp-net-npoi-epplus
        //          Response.Clear();
        //          Response.Buffer = true;
        //          Response.AddHeader("content-disposition", "attachment;filename=DataTable.csv");
        //          Response.Charset = "";
        //          Response.ContentType = "application/text";

        //          StringBuilder sb = new StringBuilder();

        //          for (int k = 0; k < dt.Columns.Count; k++)
        //          {
        //              //add separator
        //              sb.Append(dt.Columns[k].ColumnName + ',');
        //          }
        //          //append new line

        //          sb.Append("\r\n");

        //          for (int i = 0; i < dt.Rows.Count; i++)
        //          {

        //              for (int k = 0; k < dt.Columns.Count; k++)
        //              {
        //                  //add separator
        //                  sb.Append(dt.Rows[i][k].ToString().Replace(",", ";") + ',');
        //              }
        //              //append new line
        //              sb.Append("\r\n");
        //          }
        //          Response.Output.Write(sb.ToString());
        //          Response.Flush();
        //          Response.End();


        //      }
        //      else
        //      {

        //          //Create a dummy GridView

        //          var gridView1 = new GridView
        //          {
        //              AllowPaging = false,
        //              DataSource = dt
        //          };

        //          gridView1.DataBind();



        //          Response.Clear();
        //          Response.Buffer = true;
        //          Response.AddHeader("content-disposition", "attachment;filename=DataTable.xls");
        //          Response.Charset = "";
        //          Response.ContentType = "application/vnd.ms-excel";

        //          StringWriter sw = new StringWriter();
        //          HtmlTextWriter hw = new HtmlTextWriter(sw);

        //          for (int i = 0; i < gridView1.Rows.Count; i++)
        //          {
        //              //Apply text style to each Row
        //              gridView1.Rows[i].Attributes.Add("class", "textmode");
        //          }

        //          gridView1.RenderControl(hw);

        //          //style to format numbers to string

        //          string style = @"<style> .textmode { mso-number-format:\@; } </style>";

        //          Response.Write(style);
        //          Response.Output.Write(sw.ToString());
        //          Response.Flush();
        //          Response.End();             

        //      }

        //      return RedirectToAction("Index");
        //}

    } 
    
}


// public class HttpParamActionAttribute : ActionNameSelectorAttribute {
//    public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo) {
//        if (actionName.Equals(methodInfo.Name, StringComparison.InvariantCultureIgnoreCase))
//            return true;

//        if (!actionName.Equals("Action", StringComparison.InvariantCultureIgnoreCase))
//            return false;
        
//        var request = controllerContext.RequestContext.HttpContext.Request;
//        return request[methodInfo.Name] != null;
//    }
//}

racsonpDemo/Views/Query/Config.cshtml
@{
    ViewBag.Title = "Config";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Server Configuration</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
               Demo Config Elements
            </div>
            <div class="panel-body">
                <div class="row">
                 
                    <div class="col-lg-6">
                        <h1>Connection </h1>
                        <form role="form">
                            <fieldset disabled>
                                <div class="form-group">
                                    <label for="disabledSelect">Data Source Server</label>
                                    <input class="form-control" id="disabledInput" type="text" placeholder="192.168.1.1" disabled>
                                </div>
                                <div class="form-group">
                                    <label for="disabledSelect">Initial Catalog</label>
                                    <select id="disabledSelect" class="form-control">
                                        <option>Demo_Data</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="disabledSelect">User</label>
                                    <input class="form-control" id="disabledInput1" type="text" placeholder="UserQuery" disabled>
                                </div>

                                <div class="form-group">
                                    <label for="disabledSelect">Password</label>
                                    <input class="form-control" id="disabledInput3" type="text" placeholder="**********************" disabled>
                                  
                                </div> 
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox">Allow multiple users 
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary">SAVE</button>
                            </fieldset>
                        </form>
       
                    </div>
                    <!-- /.col-lg-6 (nested) -->

                    <div class="col-lg-6">
                        <form role="form">
                            <h1>INFORMATION_SCHEMA </h1>
                            <div class="form-group">
                                @*<label>INFORMATION_SCHEMA</label>*@
                                
                                <textarea class="form-control" rows="30">
                                    Table Agent
                                    Column Name	Data type
                                    --------- -------------------------------
                                    Biography		nvarchar
                                    FirstName		nvarchar
                                    Id				int
                                    LastName		nvarchar



                                    Table Producto
                                    Column Name	Data type
                                    --------- -------------------------------
                                    Id				int
                                    Nombre		nvarchar
                                    Precio			decimal
                                    Tienda			nvarchar   
                                </textarea>
                            </div>
                          
                           
                        </form>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

racsonpDemo/Views/Query/Consulta.cshtml
@*@model dynami*@
@model racsonpDemo.Models.SqlBox
@using System.Activities.Statements
@using racsonpDemo.Extensions
@using System.Data;

@{
    ViewBag.Title = "SQL QUERY BOX";

}







<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">SQL BOX .NET</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Querry Composer
            </div>

            <div class="panel-body">

                @*@using (Html.BeginForm())
                    {*@


                @*<form role="form" method="post" action="/Query/Export">*@
                <form role="form" method="post" action="/Query/Consulta">
                    @*<form role="form" method="post" >*@
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label>SQL:</label>
                        @*<textarea id="contenedorInfo" class="form-control" rows="5" disabled></textarea>*@

                        @*@Html.EditorFor(model => model.Query, new { htmlAttributes = new { @class = "form-control" } })*@

                        @Html.EditorFor(model => model.Query, new
                                                                {
                                                                    htmlAttributes = new { @class = "form-control", data_bind = "value: sqlBox.query" }
                                                                })
                        <br />
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <input type="submit" name="tipo" value="Run Query" class="btn btn-default" />
                           
                            <br />
                        </div>
                        <div class="row">
                            <div class="col-lg-6">

                                <div class="form-group">
                                    <label>Format</label>
                                    @Html.DropDownListFor(model => model.Format,
                                            new SelectList(ViewBag.Active, "Value", "Text"),
                                            "Select status",
                                            new { @class = "form-control" })
                                </div>
                                <div class="form-group">


                                    <input type="submit" name="tipo" value="Export" class="btn btn-default" />
                                    @Html.ActionLink("New Query", "Index", new { }, new { @class = "btn btn-default" })
                                  
                                </div>

                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                   
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    @*}*@

                </form>

            </div>
        </div>
    </div>
</div>


<div class="row">
    @*<input id="btnexp" type="submit" value="Export" class="btn btn-default" />*@
    <div class="col-lg-12">


        <div class="panel panel-default">
            <div class="panel-heading">
                Result

            </div>
            @*<div class="panel-heading">
                    @Html.ActionLink("Excel", "ExportExcel", new {}, new {@class = "btn btn-default"})
                    @Html.ActionLink("CSV", "ExportCsv", new {}, new {@class = "btn btn-default"})

                    @Html.ActionLink("Excel", "ExportExcel", new {id = Model.Query})
                </div>*@
            <!-- /.panel-heading -->
            @*<div style="display: none" data-bind="visible:   authors.length == 0"*@
            <div    style="display: none" data-bind="visible:   @Model.DataTable.Rows.Count  == 0" class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>

                @Model.Message
                <br />
                @Model.DataTable.Rows.Count  Rows resutls
                <br />
                @*@Html.ActionLink("New Query", "Index", new { }, new { @class = "btn btn-default" })*@
            </div>
          
            @*<div class="panel-body" style="display: none" data-bind="visible: @{Model.DataTable.Rows.Count > 0; }">*@
            <div class="panel-body" >

                <div class="table-responsive">

                    <table class="table table-hover">
                        <thead>
                            <tr>
                                @foreach (DataColumn col in Model.DataTable.Columns)
                                {
                                    <th>@col.ColumnName</th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow row in Model.DataTable.Rows)
                            {
                                <tr>
                                    @foreach (DataColumn col in Model.DataTable.Columns)
                                    {
                                        <td>@row[col.ColumnName]</td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>


                <!-- /.table-responsive -->
            </div>

            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->

</div>
@section Scripts {

    @Scripts.Render("~/bundles/jqueryval",
                "/Scripts/ViewModels/SqlBoxViewModel.js", "/Scripts/knockout-3.2.0.js")



    <script>
        var viewModel = new SqlBoxViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);

        // data: { 'format': viewModel.format,  'querry': viewModel.query },

        //success: function (data) {
        //    $('#contenedorInfo').html(data);
        //},
  
            $("#btnexp").click(function () {
                $.ajax({
                    url: "/Query/Export",
                    datatype: "text",
                    data: { 'format': viewModel.sqlBox.format,  'querry': viewModel.sqlBox.query },
                    type: "POST",
                    complete: function () {

                        $('.loading').hide();
                        var ifr = $('<iframe />').attr('src', link.attr('href')).hide().appendTo(link)
                        setTimeout(function () { ifr.remove(); }, 5000);
                    }
                        ,
                    error: function () {
                        $("#contenedorInfo").html("ERROR");
                    }
                });
            });


    </script>
}

racsonpDemo/Views/Query/Index.cshtml
@model racsonpDemo.Models.SqlBox
@using System.Data;
@using racsonpDemo.Extensions

@{
    ViewBag.Title = "SQL QUERY BOX";

}



<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">SQL BOX .NET</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Querry Composer
            </div>

            <div class="panel-body">

                @*@using (Html.BeginForm())
                    {*@



                <form role="form" method="post" action="/Query/Consulta">


                    @*@using (Html.BeginForm("Consulta", "Query", FormMethod.Get,
                            new {data_bind = "submit: validateAndSave"}))
                        {*@
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <label>SQL:</label>
                        @*<textarea class="form-control" rows="5">@Model.Query</textarea>*@

                        @*@Html.EditorFor(model => model.Query, new { htmlAttributes = new { @class = "form-control" } })*@

                        @Html.EditorFor(model => model.Query, new
                                                        {
                                                            htmlAttributes =
                                                                new { @class = "form-control", data_bind = "value: sqlBox.query" }
                                                        })

                        @Html.ValidationMessageFor(model => model.Query, "", new { @class = "text-danger" })

                        <br />


                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                             Tip: You can test query with:
                            <p class="help-block">  SELECT Id, Nombre, Precio, Tienda FROM Producto </p>
                                     OR
                            <p class="help-block"> SELECT Id, FirstName, LastName, Biography FROM Agent </p>
                        </div>


                       

                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    @*<form role="form">*@
                                    @*<div class="form-group">
                                            <label>Rows</label>
                                            <input class="form-control" id="disabledInput" type="text" placeholder="ALL" disabled>
                                            <p class="help-block">Apply a SELECT TOP N.</p>
                                        </div>*@


                                    <div class="form-group">
                                        <label>Format</label>

                                       
                                           
                                        <select class="form-control" disabled >
                                            <option>HTML</option>
                                        </select>
                                      

                                        @*@Html.DropDownListFor(model => model.Format,
                                                new SelectList(ViewBag.Active, "Value", "Text"),
                                                "Select status",
                                                new { @class = "form-control" })*@
                                    </div>



                                    <div class="form-group">
                                        @*<div class="col-md-offset-2 col-md-10" data-bind="visible: !sending()">*@
                                        <div data-bind="visible: !sending()">
                                            <button type="submit" name="tipo" value="Consulta">Run</button>
                                            @*<button type="submit" name="tipo" value="Export">Export</button>*@

                                            @*<input type="submit" name="Consulta" value="Consulta" class="btn btn-default" />*@


                                            @*<input type="submit" name="tipo" value="Consulta" class="btn btn-default" />
                                            <input type="submit" name="tipo" value="Export" class="btn btn-default" />*@
                                        </div>
                                        <div class="progress" data-bind="visible: sending">
                                            <div class="progress-bar progress-bar-info progress-bar-striped active"
                                                 role="progressbar" aria-valuenow="100"
                                                 aria-valuemin="0" aria-valuemax="100"
                                                 style="width: 100%">
                                                <span class="sr-only"></span>
                                            </div>
                                        </div>
                                    </div>



                                    @*@Html.ActionLink("Excel", "ExportExcel", new {}, new {@class = "btn btn-default"})
                                        @Html.ActionLink("CSV", "ExportCsv", new {}, new {@class = "btn btn-default"})*@

                                    @*<button type="submit" class="btn btn-default">TESTc</button>*@

                                    @*</form>*@
                                </div>
                            </div>

                        </div>

                    </div>
                    @*}*@
                </form>
            </div>
        </div>
    </div>

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval",
                "/Scripts/ViewModels/SqlBoxViewModel.js", "/Scripts/knockout-3.2.0.js")



    <script>
        var viewModel = new SqlBoxViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);


     

    </script>


}

racsonpDemo/Views/Query/View.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>